### PR TITLE
Vexflow 4.0.1

### PR DESCRIPTION
**Pull request by ronyeh**
All VexFlow types are imported with a VF prefix, for clarity (and to avoid potential collisions with Music21j classes).

Fixes https://github.com/cuthbertLab/music21j/issues/142

### CODE REVIEW

**Comment by ronyeh** [comment]
QUnit


```bash
$  grunt


Running "webpack:build" (webpack) task
(node:23306) [DEP_WEBPACK_WATCH_WITHOUT_CALLBACK] DeprecationWarning: A 'callback' argument need to be provided to the 'webpack(options, callback)' function when the 'watch' option is set. There is no way to handle the 'watch' option without a callback.
(Use `node --trace-deprecation ...` to show where the warning was created)
assets by path *.ts 211 KiB 47 assets
assets by path *.map 78.2 KiB 47 assets
assets by path stream/ 11.7 KiB
  assets by path stream/*.ts 6.66 KiB 3 assets
  assets by path stream/*.map 4.99 KiB
    asset stream/iterator.d.ts.map 2.52 KiB [compared for emit]
    asset stream/filters.d.ts.map 1.51 KiB [compared for emit]
    asset stream/makeNotation.d.ts.map 995 bytes [compared for emit]
assets by path musicxml/ 14.1 KiB
  assets by path musicxml/*.ts 8.43 KiB 2 assets
  assets by path musicxml/*.map 5.68 KiB
    asset musicxml/xmlToM21.d.ts.map 2.92 KiB [compared for emit]
    asset musicxml/m21ToXml.d.ts.map 2.76 KiB [compared for emit]
asset music21.debug.js 2.85 MiB [compared for emit] (name: main) 1 related asset
runtime modules 1.13 KiB 5 modules
modules by path ./node_modules/ 1.79 MiB
  modules by path ./node_modules/core-js/ 165 KiB 132 modules
  modules by path ./node_modules/vexflow/build/esm/ 1.19 MiB 109 modules
  modules by path ./node_modules/css-loader/dist/runtime/*.js 3.78 KiB 2 modules
modules by path ./src/ 679 KiB
  modules by path ./src/*.ts 610 KiB 47 modules
  modules by path ./src/stream/*.ts 21.6 KiB 3 modules
  modules by path ./src/musicxml/*.ts 47.2 KiB
    ./src/musicxml/xmlToM21.ts 17.9 KiB [built] [code generated]
    ./src/musicxml/m21ToXml.ts 29.3 KiB [built] [code generated]
modules by path ./css/*.css 5.63 KiB
  ./css/midiPlayer.css 524 bytes [built] [code generated]
  ./node_modules/css-loader/dist/cjs.js!./css/midiPlayer.css 5.12 KiB [built] [code generated]
webpack 5.23.0 compiled successfully in 22959 ms
```


```
$ grunt test_no_watch


Running "webpack:test" (webpack) task
assets by path ../build/src/ 315 KiB
  assets by path ../build/src/*.ts 211 KiB 47 assets
  assets by path ../build/src/*.map 78.3 KiB 47 assets
  assets by path ../build/src/stream/ 11.7 KiB 6 assets
  assets by path ../build/src/musicxml/ 14.1 KiB
    assets by path ../build/src/musicxml/*.ts 8.43 KiB 2 assets
    assets by path ../build/src/musicxml/*.map 5.69 KiB 2 assets
assets by path ../build/tests/ 8.29 KiB
  assets by path ../build/tests/moduleTests/ 5.57 KiB
    assets by path ../build/tests/moduleTests/*.map 3.81 KiB 24 assets
    assets by path ../build/tests/moduleTests/*.ts 1.76 KiB 24 assets
  asset ../build/tests/loadAll.d.ts 1.76 KiB [compared for emit]
  asset ../build/tests/loadAll.d.ts.map 979 bytes [compared for emit]
asset music21.tests.js 3.2 MiB [compared for emit] (name: main) 1 related asset
runtime modules 1.25 KiB 6 modules
modules by path ./node_modules/ 1.99 MiB
  modules by path ./node_modules/core-js/ 165 KiB 132 modules
  modules by path ./node_modules/vexflow/build/esm/ 1.19 MiB 109 modules
  modules by path ./node_modules/css-loader/dist/runtime/*.js 3.78 KiB 2 modules
modules by path ./src/ 679 KiB
  modules by path ./src/*.ts 610 KiB 47 modules
  modules by path ./src/stream/*.ts 21.6 KiB 3 modules
  modules by path ./src/musicxml/*.ts 47.2 KiB
    ./src/musicxml/xmlToM21.ts 17.9 KiB [built] [code generated]
    ./src/musicxml/m21ToXml.ts 29.3 KiB [built] [code generated]
modules by path ./tests/ 112 KiB 25 modules
modules by path ./css/*.css 5.63 KiB
  ./css/midiPlayer.css 524 bytes [built] [code generated]
  ./node_modules/css-loader/dist/cjs.js!./css/midiPlayer.css 5.12 KiB [built] [code generated]
webpack 5.23.0 compiled successfully in 27472 ms

Running "qunit:files" (qunit) task
Testing tests/gruntTest.html ......................................................................................................................OK
Access to XMLHttpRequest at 'file:///soundfonts/midi-js-soundfonts-master/FluidR3_GM/acoustic_grand_piano-ogg.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, https.
Failed to load resource: net::ERR_FAILED
>> 118 tests completed with 0 failed, 0 skipped, and 0 todo.
>> 887 assertions (in 572ms), passed: 887, failed: 0

Done.
```

**Comment by ronyeh** [comment]
I ran the grunt scripts and a inspected the HTML test pages. There are no obvious errors. However, I'm not familiar with your test cases so it's likely that there are some visual issues that need to be addressed.

Let me know if you have any questions!

You can keep this PR open for now, or you can merge it into a dev branch (to be later merged with master after your Spring term, and after any VexFlow issues are ironed out.)

**Comment by ronyeh** [comment]
Fixes https://github.com/cuthbertLab/music21j/issues/142

**Comment by ronyeh** [comment]
Hi! Just checking in on this. If you plan to upgrade to VexFlow 4, let me know. I can fix the conflicts in this PR to allow the merge to proceed.

**Comment by vanderstel** [comment]
Hi @ronyeh, can you go ahead and resolve conflicts by rebasing on top of the latest changes to master? Thanks for your contribution!

**Comment by ronyeh** [comment]
Sure, sounds good. Do you expect to merge the VexFlow 4 PR in the coming weeks?

**Comment by vanderstel** [comment]
Yep!

**Comment by mscuthbert** [comment]
This is approved and anyone with merge rights can merge after the conflicts are resolved.  THANKS @ronyeh !  :-)

**Comment by ronyeh** [comment]
Thanks @mscuthbert . I'll probably have this done and tested by Tuesday evening (August 23).

**Comment by ronyeh** [comment]
Please test this PR: https://github.com/cuthbertLab/music21j/pull/196

Instead of rebasing in this PR's branch, I created the above branch directly from your current master. I believe the commits in the above PR 196 are in a cleaner order than this PR.

I would recommend testing and merging #196, since it is based on the most recent VexFlow release: 4.0.3.

**Pull request closed without merging**
