### PR TITLE
Update music21j to latest music21

### PR DESCRIPTION
**Pull request by infojunkie**
This PR contains 3 fixes to handle the pickling format discrepancy with the latest version of music21. Specifically:

- Python objects `_classes` attribute is now called `classes`
- Python `music21.chord.Chord` `_noteArray` attribute is now called `_notes`
- The library `jsonpickleJS` also needs to be updated as per https://github.com/cuthbertLab/jsonpickleJS/issues/1

### CODE REVIEW

**Comment by infojunkie** [comment]
This PR should solve the basic case at https://github.com/cuthbertLab/music21j/issues/13

**Comment by mscuthbert** [comment]
Unfortunately, the classes fix is harder than this -- .classes is generated on the fly in the new version of Music21.  Fortunately, there should be a way around this still.

**Comment by mscuthbert** [comment]
@infojunkie -- thanks so much for the point in the right direction (And for the Chord fix) -- I'm working now on this, so don't give up hope yet!

**Comment by infojunkie** [comment]
Sure no problem, I was just cleaning up, waiting for your fix.

**Comment by mscuthbert** [comment]
Good! I re-read my message and thought that it could have been read as dismissive of what you did. Just needs a bit more tweaking.

**Pull request closed without merging**
